//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponUs
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int coupon_id { get; set; }
    
        public virtual CouponCode CouponCode { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
