//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCode()
        {
            this.CouponUses = new HashSet<CouponUs>();
        }
    
        public int id { get; set; }
        public string coupon { get; set; }
        public int discount { get; set; }
        public bool percentage { get; set; }
        public bool allow_multiple { get; set; }
        public Nullable<System.DateTime> expired_at { get; set; }
        public bool status { get; set; }
        public Nullable<int> order_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponUs> CouponUses { get; set; }
    }
}
