//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public int id { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string favicon { get; set; }
        public bool status { get; set; }
    }
}
