//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_name { get; set; }
        public string product_color { get; set; }
        public string product_size { get; set; }
        public double price { get; set; }
        public double discount { get; set; }
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
